spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=angel
spring.datasource.password=K4chorr0

spring.datasource.driver-class-name=org.postgresql.Driver

spring.application.name=app